window.BOOK_CONTENT = {
  chapters: [
    {
      id: "bab-1",
      number: "01",
      title: "Apa itu Deep Learning?",
      summary: "Apa sebenarnya kecerdasan buatan (Artificial Intelligence/AI)? Benarkah teknologi ini akan menggantikan manusia? Sejauh mana kemampuan AI saat ini, dan ke mana arah perkembangannya di masa depan?",
      status: "Tersedia",
      notebook: "notebooks/latihan-bab-01.ipynb",
      sections: [
        {
          id: "Artificial intelligence, machine learning, and deep learning",
          title: "Artificial intelligence, machine learning, and deep learning",
          paragraphs: [
            "Sebelum mempelajari konsep kecerdasan buatan (Artificial Intelligence atau AI) lebih jauh, penting untuk memahami hubungan antara AI, machine learning, dan deep learning. Ketiga istilah ini sering digunakan secara bergantian, padahal memiliki makna dan cakupan yang berbeda. AI merupakan konsep yang paling luas, machine learning merupakan bagian dari AI, sedangkan deep learning merupakan bagian dari machine learning. Dengan memahami hubungan tersebut, pembahasan mengenai AI akan menjadi lebih mudah dipahami.",
            "<figure><img src='assets/subset_ai.png' alt='Subset AI'><figcaption>Gambar 1.1: Hubungan AI, ML, dan DL</figcaption></figure>"
          ],
        },
        {
          id: "Artificial intelligence",
          title: "Artificial intelligence",
          paragraphs: [
            "Kecerdasan buatan (**Artificial Intelligence** atau *AI*) mulai berkembang sebagai bidang penelitian pada tahun 1950-an. Pada masa itu, sekelompok ilmuwan di bidang ilmu komputer mulai mempertanyakan apakah komputer dapat dibuat untuk **berpikir** seperti manusia. Pertanyaan tersebut menjadi awal lahirnya berbagai penelitian yang hingga kini masih terus berkembang.",          
            "Meskipun berbagai gagasan yang mendasari AI telah muncul beberapa tahun bahkan beberapa dekade sebelumnya, istilah artificial intelligence secara resmi diperkenalkan sebagai bidang penelitian pada tahun 1956. Saat itu, **John McCarthy**, seorang asisten profesor matematika di **Dartmouth College**, mengadakan sebuah workshop penelitian yang mempertemukan sejumlah ilmuwan untuk membahas kemungkinan menciptakan mesin yang mampu meniru kecerdasan manusia. Mereka berangkat dari gagasan bahwa setiap aspek pembelajaran dan kecerdasan pada dasarnya dapat dijelaskan secara sistematis sehingga dapat disimulasikan oleh sebuah mesin. Workshop tersebut juga bertujuan mencari cara agar mesin mampu menggunakan bahasa, membentuk konsep dan abstraksi, menyelesaikan berbagai permasalahan yang selama ini hanya dapat dilakukan manusia, serta terus meningkatkan kemampuannya sendiri.",
            "Pada akhir workshop, berbagai tujuan tersebut memang belum berhasil dicapai sepenuhnya. Namun, pertemuan tersebut menjadi tonggak penting dalam sejarah AI karena dihadiri oleh banyak ilmuwan yang kemudian menjadi pelopor di bidang ini. Dari sinilah lahir revolusi intelektual yang hingga saat ini masih terus mendorong perkembangan teknologi kecerdasan buatan.",
            "Secara sederhana, AI dapat didefinisikan sebagai :",
            "> Upaya untuk mengotomatisasi tugas-tugas intelektual yang umumnya dilakukan oleh manusia", 
            "AI merupakan bidang yang sangat luas yang mencakup **machine learning** dan **deep learning**, serta berbagai pendekatan lain yang tidak selalu melibatkan proses pembelajaran.",
            "Sebelum tahun 1980-an, sebagian besar penelitian AI bahkan belum berfokus pada konsep pembelajaran (learning). Sebagai contoh, program catur pada masa awal dikembangkan menggunakan aturan-aturan yang ditulis secara eksplisit oleh programmer sehingga belum termasuk ke dalam kategori machine learning. Pada saat itu, banyak peneliti meyakini bahwa kecerdasan buatan setingkat manusia dapat diwujudkan dengan menyusun kumpulan aturan yang sangat banyak untuk memanipulasi pengetahuan yang tersimpan dalam basis data. Pendekatan ini dikenal sebagai **[symbolic AI| Pendekatan AI yang menggunakan seperangkat aturan logika dan simbol untuk memproses informasi (If-Else)]** dan menjadi paradigma utama dalam penelitian AI sejak tahun 1950-an hingga akhir 1980-an. Popularitasnya mencapai puncak pada era berkembangnya [expert systems| (Sistem Pakar) adalah salah satu cabang dari symblic AI yang dirancang untuk meniru kemampuan pengambilan keputusan seorang pakar manusia pada bidang tertentu dengan menggunakan kumpulan aturan (rule-based system).] pada dekade 1980-an.",
            "Meskipun symbolic AI berhasil menyelesaikan berbagai permasalahan yang memiliki aturan jelas dan bersifat logis, seperti permainan catur, pendekatan ini mengalami kesulitan ketika diterapkan pada permasalahan yang lebih kompleks dan tidak memiliki aturan yang pasti, seperti klasifikasi gambar, pengenalan suara, maupun penerjemahan bahasa alami. Keterbatasan tersebut mendorong lahirnya pendekatan baru, yaitu machine learning, yang kemudian secara bertahap menggantikan dominasi symbolic AI dalam berbagai bidang penerapan AI."
          ]
        },
        {
          id: "Machine learning",
          title: "Machine learning",
          paragraphs: [
            "Pada [era Victoria | (Victorian era) adalah kurun waktu ketika Ratu Victoria memerintah Kerajaan Inggris, tepatnya dari tahun 1837 hingga 1901.] di Inggris, Lady Ada Lovelace merupakan sahabat sekaligus rekan kolaborasi Charles Babbage, penemu [Analytical Engine|Rancangan komputer mekanis serbaguna pertama di dunia yang didesain oleh Charles Babbage pada tahun 1837; menggunakan sistem kartu berlubang (punch cards) dan menjadi cikal bakal arsitektur komputer modern.], komputer mekanis serbaguna pertama yang pernah dirancang. Meskipun sangat visioner dan jauh melampaui zamannya, Analytical Engine pada saat dirancang pada dekade 1830-an dan 1840-an sebenarnya belum dimaksudkan sebagai komputer serbaguna, karena konsep komputasi serbaguna saat itu masih belum dikenal. Mesin tersebut hanya dirancang sebagai alat untuk mengotomatiskan berbagai perhitungan dalam bidang analisis matematika melalui mekanisme mekanis, sehingga diberi nama Analytical Engine.",
            "Dengan demikian, mesin ini merupakan hasil pengembangan dari berbagai upaya sebelumnya untuk merepresentasikan operasi matematika menggunakan roda gigi, seperti [Pascaline|Alat hitung mekanis (kalkulator) roda gigi pertama di dunia yang diciptakan oleh Blaise Pascal pada tahun 1642; dirancang khusus untuk melakukan operasi penjumlahan dan pengurangan secara otomatis.] dan [Step Reckoner|Alat hitung mekanis pertama yang dapat melakukan empat operasi aritmatika dasar (penjumlahan, pengurangan, perkalian, pembagian); diciptakan oleh Gottfried Wilhelm Leibniz pada tahun 1673 menggunakan mekanisme silinder bergerigi (Leibniz wheel)], yang merupakan penyempurnaan dari Pascaline. Pascaline sendiri dirancang oleh Blaise Pascal pada tahun 1642 ketika usianya baru 19 tahun. Alat ini merupakan kalkulator mekanis pertama di dunia yang mampu melakukan operasi penjumlahan dan pengurangan. Selanjutnya, Leibniz mengembangkan Step Reckoner yang menambahkan kemampuan untuk melakukan perkalian dan pembagian secara mekanis.",
            "Pada tahun 1843, Ada Lovelace mengemukakan pandangannya mengenai Analytical Engine sebagai berikut:",
            "> **Analytical Engine** sama sekali tidak memiliki kemampuan untuk menciptakan sesuatu yang benar-benar baru. Mesin ini hanya dapat melakukan apa pun yang kita perintahkan untuk dikerjakan. Perannya adalah membantu kita memanfaatkan pengetahuan yang telah kita miliki.",
            "Bahkan setelah hampir dua abad berlalu, pernyataan Lady Lovelace tersebut tetap menarik untuk direnungkan. Apakah komputer serbaguna benar-benar dapat **menciptakan** sesuatu yang baru, ataukah selamanya hanya akan menjalankan serangkaian proses yang sepenuhnya telah dipahami oleh manusia? Mungkinkah komputer memiliki pemikiran yang orisinal? Dapatkah komputer belajar dari pengalaman? Mampukah komputer menunjukkan kreativitas?",
            "Pernyataan tersebut kemudian dikutip oleh pelopor kecerdasan buatan, Alan Turing, dalam makalahnya pada tahun 1950 yang berjudul [Computing Machinery and Intelligence](https://courses.cs.umbc.edu/471/papers/turing.pdf). Dalam makalah tersebut, Turing menyebut pandangan Ada Lovelace sebagai Lovelace's Objection, yaitu argumen bahwa komputer tidak dapat menciptakan sesuatu yang benar-benar baru, melainkan hanya menjalankan instruksi yang diberikan. Makalah yang sama juga memperkenalkan [Turing Test|Metode pengujian kecerdasan kecerdasan buatan (AI) yang diusulkan oleh Alan Turing pada tahun 1950; bertujuan untuk menguji apakah suatu mesin mampu menunjukkan perilaku cerdas yang tidak dapat dibedakan dari manusia dalam percakapan berbasis teks.] serta berbagai konsep yang menjadi dasar perkembangan kecerdasan buatan (Artificial Intelligence/AI). Pada masa itu, Turing mengemukakan gagasan yang kontroversial bahwa, pada prinsipnya, komputer dapat dirancang untuk meniru berbagai aspek kecerdasan manusia.",
            "Agar komputer dapat melakukan tugas tertentu, seorang programmer menuliskan serangkaian aturan atau instruksi yang disebut program komputer. Program tersebut mengubah data masukan menjadi keluaran yang diinginkan. Prinsip ini serupa dengan cara Lady Ada Lovelace menyusun langkah-langkah yang harus dijalankan oleh Analytical Engine untuk menyelesaikan suatu perhitungan.",
            "Machine learning membalik pendekatan tersebut. Alih-alih manusia yang menentukan seluruh aturan secara eksplisit, mesin diberikan data masukan beserta jawaban yang benar, kemudian mesin mempelajari sendiri pola-pola di dalam data tersebut untuk menyimpulkan aturan yang diperlukan",
            "<figure><img src='assets/cara_lama_vs_machine_learning.png' alt='pendekatan lama vs machine learning'><figcaption>Gambar 1.2: Perbedaan pendekatan lama dan pendekatan machine learning</figcaption></figure>",
            "Berbeda dengan program komputer biasa, sistem machine learning tidak diberi aturan secara langsung. Sebaliknya, sistem dilatih menggunakan banyak contoh data. Dari contoh-contoh tersebut, sistem mempelajari pola yang kemudian digunakan untuk menyelesaikan tugas secara otomatis.",
            "Sebagai contoh, jika Anda ingin mengotomatiskan pemberian label pada foto-foto liburan, Anda dapat melatih sistem machine learning menggunakan banyak foto yang telah diberi label oleh manusia. Dari contoh-contoh tersebut, sistem mempelajari pola yang menghubungkan karakteristik gambar dengan label tertentu, seperti landscape (pemandangan) atau food (makanan).",
            "Meskipun machine learning baru mulai berkembang pesat pada dekade 1990-an, bidang ini dengan cepat menjadi cabang kecerdasan buatan (AI) yang paling populer dan paling berhasil. Perkembangan tersebut didorong oleh tersedianya perangkat keras yang semakin cepat serta kumpulan data (dataset) yang semakin besar.",
            "Machine learning memiliki keterkaitan erat dengan statistika matematika, tetapi keduanya berbeda dalam beberapa aspek penting. Hubungan ini dapat dianalogikan seperti hubungan antara ilmu kedokteran dan kimia. Kedokteran memang berlandaskan kimia, tetapi tidak dapat sepenuhnya direduksi menjadi kimia karena mempelajari sistem yang memiliki karakteristik dan prinsipnya sendiri.",
            "Berbeda dengan statistika klasik, machine learning umumnya menangani kumpulan data yang sangat besar dan kompleks, misalnya jutaan gambar digital yang masing-masing terdiri atas puluhan ribu piksel. Pada skala seperti ini, metode analisis statistik tradisional, seperti analisis Bayesian, sering kali menjadi tidak praktis untuk diterapkan.",
            "Akibatnya, machine learning, khususnya deep learning, memiliki landasan teori matematika yang relatif terbatas. Bidang ini lebih banyak berkembang sebagai disiplin rekayasa (engineering) yang berfokus pada penerapan. Berbeda dengan fisika teoretis atau matematika yang menekankan pengembangan teori, kemajuan machine learning terutama didorong oleh hasil eksperimen serta perkembangan perangkat lunak dan perangkat keras."
          ],
        },
        {
          id: "Mempelajari pola dan representasi dari data",
          title: "Mempelajari pola dan representasi dari data",
          paragraphs: [
            "Untuk mendefinisikan deep learning dan memahami perbedaan antara deep learning dengan pendekatan machine learning lainnya, pertama-tama kita perlu memahami apa yang dilakukan oleh algoritma machine learning. Seperti telah dijelaskan sebelumnya, machine learning bertujuan untuk menemukan aturan dalam menyelesaikan suatu tugas pemrosesan data berdasarkan contoh-contoh hasil yang diharapkan. Oleh karena itu, agar machine learning dapat bekerja, diperlukan tiga komponen utama:",
            "- **Data masukan** : Misalnya, jika tugasnya adalah pengenalan suara (speech recognition), maka data masukan dapat berupa berkas audio yang berisi rekaman suara seseorang. Jika tugasnya adalah pemberian label pada gambar (image tagging), maka data masukan berupa gambar.",
            "- **Contoh keluaran yang diharapkan** (expected outputs) : Pada tugas pengenalan suara, contoh keluaran dapat berupa transkrip hasil penulisan manusia dari rekaman suara tersebut. Sementara itu, pada tugas klasifikasi atau pelabelan gambar, keluaran yang diharapkan dapat berupa label seperti anjing, kucing, dan sebagainya.",
            "- **Cara untuk mengukur** seberapa besar perbedaan antara keluaran yang dihasilkan algoritma dengan keluaran yang diharapkan — Pengukuran ini diperlukan untuk mengetahui tingkat kesalahan (error) algoritma. Nilai pengukuran tersebut kemudian digunakan sebagai sinyal umpan balik (feedback) untuk menyesuaikan cara kerja algoritma. Proses penyesuaian inilah yang disebut sebagai pembelajaran (learning).",
            "Model machine learning mengubah data masukan menjadi keluaran berdasarkan pola yang dipelajari dari contoh-contoh pasangan data masukan dan keluaran yang telah diketahui sebelumnya. Oleh karena itu, tujuan utama machine learning maupun deep learning adalah mempelajari cara merepresentasikan data masukan agar dapat menghasilkan keluaran yang semakin mendekati hasil yang diharapkan.",
            "Sebelum melanjutkan pembahasan, penting untuk memahami konsep representasi. Representasi adalah cara suatu data disajikan atau dikodekan. Misalnya, sebuah gambar berwarna dapat direpresentasikan dalam format [RGB | (Red, Green, Blue) adalah model warna berbasis additive color (pencampuran cahaya) yang digunakan untuk menampilkan gambar pada perangkat elektronik seperti layar monitor, televisi, smartphone, dan kamera digital] atau [HSV | (Hue, Saturation, Value) adalah model warna yang merepresentasikan persepsi manusia dengan membagi warna menjadi tiga komponen: Hue (jenis warna), Saturation (kepekatan/kemurnian), dan Value (kecerahan). Model ini sering digunakan dalam computer vision dan pengolahan citra karena mempermudah deteksi objek berdasarkan warna tanpa terpengaruh perubahan intensitas cahaya.]. Keduanya merupakan representasi yang berbeda dari gambar yang sama.",
            "Beberapa tugas lebih mudah dilakukan pada representasi tertentu. Misalnya, memilih piksel berwarna merah lebih mudah menggunakan representasi RGB, sedangkan mengatur tingkat saturasi lebih mudah menggunakan representasi HSV. Oleh karena itu, model machine learning berusaha mempelajari representasi data yang paling sesuai agar tugas dapat diselesaikan dengan lebih mudah.",
            "Agar lebih mudah dipahami, perhatikan sebuah sistem koordinat yang terdiri atas sumbu x dan sumbu y, serta sejumlah titik yang direpresentasikan berdasarkan koordinatnya pada bidang (x, y), seperti yang ditunjukkan pada Gambar 1.3.",
            "<figure><img src='assets/contoh_sampel_data.png' alt='Contoh Sampel Data'><figcaption>Gambar 1.3 : Contoh Sampel Gambar</figcaption></figure>",
            "Seperti yang terlihat, terdapat beberapa titik berwarna biru dan beberapa titik berwarna hitam. Misalkan kita ingin mengembangkan sebuah algoritma yang dapat menerima koordinat (x, y) dari suatu titik sebagai masukan, kemudian menentukan apakah titik tersebut kemungkinan termasuk ke dalam kelompok titik hitam atau titik biru. Dalam kasus ini:",
            "- **Data masukan (input)** adalah koordinat (x, y) dari setiap titik.",
            "- **Keluaran yang diharapkan** (expected output) adalah warna dari setiap titik, yaitu hitam atau putih.",
            "- **Cara untuk mengukur kinerja algoritma** dapat berupa persentase titik yang berhasil diklasifikasikan dengan benar.",
            "Yang kita perlukan adalah representasi baru dari data yang mampu memisahkan titik-titik biru dan titik-titik hitam secara jelas. Salah satu transformasi yang dapat digunakan, di antara berbagai kemungkinan lainnya, adalah [perubahan sistem koordinat | perubahan sistem koordinat merujuk pada transformasi ruang fitur (feature space transformation) untuk mengubah representasi data agar lebih mudah dipisahkan berdasarkan kelasnya.] (coordinate change), seperti yang ditunjukkan pada Gambar 1.4.",
            "<figure><img src='assets/perubahan_koordinat.png' alt='Perubahaan Koordinat'><figcaption>Gambar 1.4 : Perubahan Koordinat</figcaption></figure>",
            "Dalam sistem koordinat yang baru ini, koordinat setiap titik dapat dianggap sebagai representasi baru dari data kita. Dan representasi ini sangat baik! Dengan representasi ini, masalah klasifikasi titik hitam dan biru dapat dinyatakan dengan aturan yang sangat sederhana: Titik hitam memiliki nilai x > 0, sedangkan titik biru memiliki nilai x < 0, seperti digambarkan pada gambar 1.4 paling kanan. Kombinasi antara representasi baru dan aturan sederhana ini berhasil menyelesaikan masalah klasifikasi dengan sangat baik.",
            "Pada contoh ini, kita menentukan perubahan sistem koordinat tersebut secara manual. Kita menggunakan kemampuan berpikir kita untuk menemukan representasi data yang sesuai. Pendekatan ini mungkin akan terkesan mudah untuk masalah yang sangat sederhana. Namun, bagaimana jika tugasnya adalah mengklasifikasikan gambar angka tulisan tangan? Apakah kita bisa membuat sendiri serangkaian transformasi gambar yang dapat dijalankan komputer untuk membedakan angka 6 dengan 8, atau 1 dengan 7, pada berbagai macam gaya tulisan tangan?",
            "Sampai batas tertentu, hal itu memang memungkinkan. Misalnya, kita dapat membuat aturan berdasarkan representasi tertentu, seperti menghitung jumlah lingkaran tertutup pada sebuah angka atau menggunakan histogram piksel vertikal dan horizontal. Pendekatan seperti ini cukup efektif untuk membedakan angka-angka tulisan tangan.",
            "Namun, menemukan representasi yang benar-benar berguna dan efektif secara manual bukanlah pekerjaan yang mudah. Selain itu, sistem berbasis aturan yang dihasilkan cenderung rapuh dan sulit dipelihara. Setiap kali muncul contoh tulisan tangan baru yang tidak sesuai dengan aturan yang telah dibuat, kita harus menambahkan transformasi data dan aturan baru, sekaligus memastikan aturan tersebut tidak bertentangan atau menimbulkan masalah dengan semua aturan yang telah dibuat sebelumnya.",
            "Mungkin sekarang Anda berpikir, jika proses ini begitu rumit, mengapa tidak kita otomatisasi saja? mencari secara otomatis berbagai representasi data dan aturan yang dapat digunakan untuk mengklasifikasikan data tersebut, kemudian menguji setiap hasil pada data pengujian (development dataset) dan memilih yang memiliki tingkat akurasi tertinggi? Jika melakukan hal tersebut, berarti kita sedang menerapkan machine learning.",
            "Dalam machine learning, pembelajaran (learning) adalah proses mencari secara otomatis cara terbaik untuk merepresentasikan data. Pencarian ini menggunakan umpan balik (feedback signal) untuk memperoleh representasi data yang paling efektif dalam menyelesaikan suatu tugas.",
            "Transformasi tersebut dapat berupa perubahan sistem koordinat, seperti pada contoh klasifikasi titik dalam bidang 2D, atau mengubah gambar menjadi bentuk lain, misalnya menggunakan histogram piksel atau menghitung jumlah lingkaran tertutup pada angka tulisan tangan. Selain itu, transformasi juga dapat berupa proyeksi linear, translasi, operasi nonlinier, maupun berbagai bentuk transformasi lainnya.",
            "Algoritma machine learning pada umumnya tidak menemukan transformasi baru dengan sendirinya. Sebaliknya, algoritma hanya mencari kombinasi terbaik dari sekumpulan transformasi yang telah ditentukan sebelumnya. Kumpulan semua kemungkinan transformasi tersebut disebut ruang hipotesis (hypothesis space). Sebagai contoh, pada kasus klasifikasi titik dalam koordinat 2D, ruang hipotesisnya adalah seluruh kemungkinan perubahan sistem koordinat yang dapat diterapkan pada data.",
            "Singkatnya, machine learning adalah proses mencari representasi data dan aturan yang paling efektif untuk menyelesaikan suatu tugas dengan mengeksplorasi berbagai kemungkinan yang telah ditentukan sebelumnya, di mana pemilihannya didasarkan pada umpan balik (feedback signal). Gagasan sederhana ini memungkinkan kita menyelesaikan beragam permasalahan yang kompleks, mulai dari kendaraan otonom (self-driving car) hingga sistem tanya jawab berbasis bahasa alami.",
            "Setelah memahami apa yang dimaksud dengan learning dalam machine learning, selanjutnya kita akan mempelajari apa yang membuat deep learning menjadi pendekatan yang istimewa dibandingkan metode machine learning lainnya."
          ]
        },
        {
          id: "Deep dalam Deep Lerning",
          title: "Deep dalam Deep Lerning",
          paragraphs :[
            "Deep learning merupakan salah satu cabang dari machine learning. Pendekatan ini menawarkan cara baru untuk mempelajari representasi data dengan menyusun proses pembelajaran ke dalam beberapa lapisan, sehingga setiap lapisan menghasilkan representasi yang lebih bermakna.Istilah deep pada deep learning tidak mengacu pada tingkat pemahaman yang lebih mendalam, tetapi pada banyaknya lapisan yang digunakan untuk mempelajari representasi data.Jumlah lapisan yang digunakan untuk membentuk model disebut sebagai kedalaman (depth) model. Oleh karena itu, istilah yang lebih tepat sebenarnya dapat berupa layered representation learning atau hierarchical representation learning. Deep learning modern umumnya menggunakan puluhan hingga ratusan lapisan representasi yang dipelajari secara otomatis dari data pelatihan. Sebaliknya, pendekatan machine learning tradisional biasanya hanya mempelajari satu atau dua tingkat representasi data sebelum menghasilkan prediksi. Oleh karena itu, pendekatan tersebut sering disebut sebagai [shallow learning | adalah pendekatan pemodelan machine learning yang memetakan data dari input langsung ke output melalui satu tahap pemrosesan sederhana, tanpa membongkar atau mempelajari fitur data secara berjenjang (hierarchical features)].",
            "Dalam deep learning, representasi berlapis tersebut dipelajari menggunakan model yang disebut jaringan saraf tiruan (neural network), yang tersusun dari lapisan-lapisan yang saling bertumpuk. Istilah neural network memang berasal dari bidang neurobiologi, karena beberapa konsep dasar deep learning dikembangkan dengan mengambil inspirasi dari cara kerja otak, khususnya [korteks visual|(Visual Cortex) adalah bagian dari otak besar (cerebrum) yang berfungsi sebagai pusat pemrosesan informasi visual/penglihatan Utama. Ketika mata kamu melihat sesuatu, mata sebenarnya hanya menangkap cahaya dan mengubahnya menjadi sinyal listrik. Sinyal listrik tersebut kemudian dikirim ke korteks visual untuk diolah, diterjemahkan, dan diinterpretasikan sehingga kamu paham apa yang sedang kamu lihat (misalnya mengenali bentuk, warna, gerakan, atau wajah seseorang)]. Namun, model deep learning bukanlah model yang meniru cara kerja otak. Hingga saat ini, tidak terdapat bukti bahwa otak manusia menggunakan mekanisme pembelajaran yang sama seperti yang diterapkan pada model deep learning modern. Beberapa artikel populer sering menyatakan bahwa deep learning bekerja seperti otak atau dimodelkan berdasarkan otak, padahal anggapan tersebut kurang tepat. Pemahaman seperti ini justru dapat membingungkan bagi pemula. Oleh karena itu, deep learning sebaiknya dipahami sebagai kerangka kerja matematis untuk mempelajari representasi dari data, tanpa perlu mengaitkannya secara langsung dengan mekanisme biologis pada otak.",
            "Lalu, seperti apa representasi yang dipelajari oleh algoritma deep learning? Untuk memahaminya, perhatikan bagaimana sebuah jaringan saraf yang terdiri atas beberapa lapisan (lihat Gambar 1.5) secara bertahap mentransformasikan citra sebuah angka hingga akhirnya mampu mengenali angka tersebut.",
            "<figure><img src='assets/klasifikasi_ankga_DL.png' alt='Klasifikasi Angka dengan Deep Learning'><figcaption>Gambar 1.5 : Klasifikasi Angka dengan Deep learning</figcaption></figure>",
            "Seperti yang ditunjukkan pada Gambar 1.6, citra digit diproses oleh jaringan menjadi representasi yang semakin berbeda dari citra aslinya, namun semakin kaya akan informasi yang relevan terhadap hasil prediksi akhir. Jaringan mendalam (deep network) dapat dipandang sebagai proses penyaringan informasi yang berlangsung secara bertahap, di mana informasi melewati serangkaian lapisan hingga secara bertahap menjadi semakin murni, yaitu semakin berguna untuk menyelesaikan suatu tugas",
            "<figure><img src='assets/representasi_deep.png' alt='Representasi mendalam yang dipelajari oleh model klasifikasi digit.'><figcaption>Gambar 1.6 : Representasi mendalam yang dipelajari oleh model klasifikasi digit.</figcaption></figure>",
            "Secara teknis, itulah yang dimaksud dengan deep learning, yaitu pendekatan bertahap untuk mempelajari representasi data. Meskipun konsep ini sederhana, pada kenyataannya mekanisme yang sangat sederhana sekalipun, ketika diterapkan pada skala yang cukup besar, dapat menghasilkan kemampuan yang tampak seolah-olah seperti sebuah keajaiban.",
          ]
        },
        {
          id : "Memahami Cara Kerja Deep Learning dalam Tiga Gambar",
          title : "Memahami Cara Kerja Deep Learning dalam Tiga Gambar",
          paragraphs : [
            "Pada tahap ini, Anda telah mengetahui bahwa machine learning bertujuan menghubungkan masukan (misalnya gambar) dengan targetnya (misalnya label kucing) melalui pembelajaran dari banyak contoh pasangan masukan dan target. Anda juga telah mengetahui bahwa jaringan saraf dalam (deep neural network) melakukan proses tersebut melalui serangkaian transformasi data sederhana yang tersusun secara berlapis (layer), dan bahwa transformasi-transformasi tersebut dipelajari melalui paparan terhadap banyak contoh data. Sekarang, mari kita lihat secara lebih konkret bagaimana proses pembelajaran tersebut berlangsung.",
            "Cara sebuah layer memproses data masukannya ditentukan oleh bobot (weights) yang dimilikinya, yang pada dasarnya merupakan sekumpulan nilai numerik. Dalam istilah teknis, kita mengatakan bahwa transformasi yang dilakukan oleh sebuah layer ditentukan oleh bobotnya (lihat Gambar 1.7). (Bobot juga terkadang disebut sebagai parameter dari sebuah layer.) Dalam konteks ini, pembelajaran (learning) berarti mencari nilai yang paling sesuai untuk setiap bobot yang dimiliki oleh seluruh layer dalam jaringan, sehingga jaringan dapat menghasilkan keluaran yang benar untuk setiap contoh masukan.Namun, ada satu tantangan: sebuah jaringan saraf dalam dapat memiliki puluhan juta parameter. Menemukan nilai yang tepat untuk seluruh parameter tersebut tampak seperti tugas yang sangat sulit, terutama karena perubahan pada nilai satu parameter saja dapat memengaruhi perilaku semua parameter lainnya.",
            "<figure><img src='assets/pencarian_nilai_bobot.png' alt='jaringan saraf di tentukan oleh bobotnya.'><figcaption>Gambar 1.7 : jaringan saraf di tentukan oleh bobotnya.</figcaption></figure>",
            "Untuk dapat mengatur keluaran suatu sistem, pertama-tama kita perlu dapat mengamatinya. Dalam konteks jaringan saraf, untuk mengatur keluaran yang dihasilkan oleh jaringan, kita perlu mengetahui seberapa jauh keluaran tersebut menyimpang dari hasil yang diharapkan. Inilah peran [loss function| Sebuah fungsi matematika yang mengukur sejauh mana prediksi yang dihasilkan oleh model deep learning menyimpang atau berbeda dari nilai sebenarnya (ground truth)] pada jaringan, yang terkadang juga disebut sebagai [objective function|Sebuah fungsi matematis yang menghitung satu nilai angka (skalar) dari parameter model, yang digunakan sebagai acuan utama untuk dioptimalkan—baik dengan cara diminimalkan (dikurangi kesalahannya) atau dimaksimalkan (ditingkatkan performanya).] atau [cost function|Sebuah fungsi matematis yang mengukur total akumulasi kesalahan dari suatu model machine learning pada seluruh dataset pelatihan (training dataset).].",
            "Loss function membandingkan prediksi jaringan dengan target sebenarnya, kemudian menghitung seberapa baik jaringan menghasilkan prediksi tersebut (lihat Gambar 1.8).",
            "<figure><img src='assets/loss_function.png' alt='Pengukuran kualitas output dengan fungsi loss.'><figcaption>Gambar 1.8 : Pengukuran kualitas output dengan fungsi loss.</figcaption></figure>",
            "Dalam deep learning, nilai yang dihasilkan oleh loss function digunakan sebagai sinyal umpan balik untuk menyesuaikan nilai weight sedikit demi sedikit ke arah yang dapat menurunkan nilai loss pada contoh yang sedang diproses (lihat Gambar 1.9). Penyesuaian ini dilakukan oleh optimizer melalui algoritma yang disebut Backpropagation, yang merupakan algoritma utama dalam deep learning. Bab berikutnya akan menjelaskan secara lebih rinci bagaimana backpropagation bekerja.",
            "<figure><img src='assets/pembaruan_bobot.png' alt='Nilai loss digunakan sebagai sinyal umpan balik untuk menyesuaikan bobot'><figcaption>Gambar 1.9 : Nilai loss digunakan sebagai sinyal umpan balik untuk menyesuaikan bobot.</figcaption></figure>",
            "Pada awal pelatihan, bobot (weight) pada jaringan diberikan nilai secara acak, sehingga model hanya melakukan serangkaian transformasi acak terhadap input. Akibatnya, output yang dihasilkan model masih jauh dari target yang seharusnya, sehingga nilai loss juga sangat tinggi. Namun, setiap kali model memproses satu data pelatihan, nilai weight pada jaringan akan sedikit disesuaikan ke arah yang benar sehingga nilai loss semakin menurun. Proses ini disebut training loop. Jika proses tersebut diulangi dalam jumlah yang cukup banyak (biasanya puluhan kali untuk ribuan data pelatihan), akan diperoleh nilai weight yang dapat meminimalkan loss function. Model dengan nilai loss yang minimal adalah model yang menghasilkan output sedekat mungkin dengan target sebenarnya. Model seperti ini disebut model yang telah dilatih (trained model). Sekali lagi, mekanismenya sederhana, tetapi ketika diterapkan dalam skala besar, hasilnya dapat terlihat seperti sebuah keajaiban."
          ]
        },
        {
          id : "Apa yang membuat deep learning berbeda",
          title : "Apa yang membuat deep learning berbeda",
          paragraphs: [
            "Apa yang membuat deep neural networks begitu istimewa hingga banyak perusahaan tertarik berinvestasi di dalamnya dan banyak peneliti memilih untuk mendalaminya? Apakah kita masih akan menggunakan deep neural networks dalam 20 tahun ke depan?",
            "Deep learning memiliki sejumlah keunggulan yang membuatnya dianggap sebagai sebuah revolusi dalam bidang kecerdasan buatan, dan teknologi ini tampaknya akan terus digunakan di masa depan. Mungkin beberapa dekade dari sekarang kita tidak lagi menggunakan neural networks dalam bentuk seperti yang kita kenal saat ini, tetapi apa pun teknologi yang menggantikannya kemungkinan besar akan mewarisi secara langsung konsep-konsep inti dari deep learning modern. Karakteristik penting tersebut secara umum dapat dikelompokkan ke dalam tiga kategori utama:",
            "* **Simplicity (Kesederhanaan)** — Deep learning membuat proses pemecahan masalah menjadi jauh lebih mudah karena mengotomatiskan salah satu tahapan yang sebelumnya paling penting dalam alur kerja machine learning, yaitu feature engineering atau rekayasa fitur. Teknik machine learning sebelumnya—yang disebut shallow learning—hanya melakukan transformasi terhadap data masukan ke dalam satu atau dua ruang representasi secara bertahap. Pendekatan tersebut tidak cukup mampu merepresentasikan sebagian besar permasalahan yang kompleks. Oleh karena itu, manusia harus melakukan banyak upaya agar data masukan dapat diproses dengan lebih baik oleh metode-metode tersebut. Mereka harus secara manual menentukan dan merancang representasi yang tepat untuk data yang digunakan. Proses ini disebut feature engineering. Sebaliknya, deep learning sepenuhnya mengotomatiskan tahap tersebut. Dengan deep learning, seluruh fitur dapat dipelajari secara otomatis dalam satu proses, sehingga kita tidak perlu lagi merancangnya secara manual. Hal ini membuat alur kerja machine learning menjadi jauh lebih sederhana. Proses yang sebelumnya membutuhkan pipeline yang kompleks dan terdiri dari banyak tahapan kini sering kali dapat digantikan oleh satu model deep learning yang sederhana dan bekerja secara end-to-end.",
            "* **Skalabilitas (Scalability)** — Deep learning sangat memungkinkan untuk diparalelkan pada GPU atau perangkat keras yang dirancang khusus untuk machine learning. Artinya, proses komputasi selama pelatihan, seperti perkalian matriks, konvolusi, dan operasi tensor, dapat dibagi menjadi banyak operasi kecil yang dikerjakan secara bersamaan oleh banyak core komputasi. Hal ini memungkinkan GPU memproses sejumlah besar data dalam waktu yang relatif lebih singkat dibandingkan jika seluruh perhitungan dilakukan secara berurutan. Selain itu, model deep learning dilatih dengan mengiterasikan data dalam kelompok-kelompok kecil (small batches), sehingga model dapat dilatih menggunakan dataset dengan ukuran yang sangat besar tanpa harus memuat seluruh dataset ke dalam memori sekaligus. Dengan demikian, kemampuan komputasi paralel menjadi salah satu faktor utama yang menentukan seberapa besar model dan dataset yang dapat diproses. Perkembangan kemampuan perangkat keras yang terus meningkat, sejalan dengan [Hukum Moore | Prediksi oleh Gordon Moore (salah satu pendiri Intel) pada tahun 1965 yang menyatakan bahwa jumlah transistor—komponen sakelar elektronik pengendali data biner pada prosesor—akan berlipat ganda setiap dua tahun sekali, sehingga melipatgandakan kecepatan komputasi sekaligus menekan biaya produksi perangkat komputer.], semakin memperluas batas tersebut.",
            "* **Fleksibilitas dan penggunaan kembali (Versatility and reusability)** — Berbeda dengan banyak pendekatan machine learning sebelumnya, model deep learning dapat dilatih menggunakan data tambahan tanpa harus memulai proses pelatihan dari awal. Hal ini membuatnya sesuai untuk continuous online learning, yaitu pembelajaran berkelanjutan dari data baru, yang merupakan karakteristik penting bagi model produksi berukuran sangat besar. Selain itu, model deep learning yang telah dilatih dapat digunakan kembali dan diadaptasi untuk berbagai keperluan. Inilah gagasan utama di balik “foundation models”, yaitu model berukuran besar yang dilatih menggunakan data dalam jumlah sangat besar dan dapat digunakan untuk berbagai tugas baru dengan sedikit pelatihan tambahan, atau bahkan tanpa pelatihan ulang sama sekali.",
          
          ]
        },
        {
          id:"Era Generatif AI",
          title : "Era Generatif AI",
          paragraphs : [
            "Mungkin contoh deep learning yang paling dikenal saat ini adalah maraknya aplikasi AI generatif—mulai dari asisten chatbot seperti ChatGPT, Gemini, dan Claude, hingga layanan pembuatan gambar seperti Midjourney.Aplikasi-aplikasi ini telah menarik perhatian publik melalui kemampuannya menghasilkan konten yang informatif atau bahkan kreatif sebagai respons terhadap prompt sederhana, sehingga batas antara kreativitas manusia dan mesin menjadi semakin samar.",
            "AI generatif didukung oleh model AI berukuran sangat besar yang disebut model fondasi (foundation model). Model ini dilatih menggunakan data dalam jumlah sangat besar dan beragam untuk mempelajari pola umum dalam teks, gambar, dan jenis data lainnya. Model fondasi belajar untuk merekonstruksi teks dan gambar yang diberikan sebagai masukan—misalnya, merekonstruksi gambar yang tajam dari versi gambar yang memiliki noise, memprediksi kata berikutnya dalam sebuah kalimat, dan sebagainya. Dengan demikian, target pada Gambar 1.8 diperoleh dari data masukan itu sendiri. Pendekatan ini disebut pembelajaran mandiri (self-supervised learning), yang memungkinkan model-model tersebut memanfaatkan data dalam jumlah sangat besar tanpa memerlukan label yang dibuat secara manual. Setelah dilatih, model fondasi dapat digunakan sebagai dasar untuk berbagai tugas tanpa perlu dilatih dari awal untuk setiap tugas. Dengan menghilangkan kebutuhan akan anotasi data secara manual, yang sebelumnya menjadi salah satu hambatan utama dalam machine learning, pendekatan ini telah memungkinkan skala pelatihan yang belum pernah dicapai sebelumnya. Beberapa model fondasi bahkan memiliki ratusan miliar parameter dan dilatih menggunakan lebih dari 1 petabyte data, dengan biaya yang mencapai puluhan juta dolar.",
            "Model fondasi ini dapat dipandang sebagai semacam kumpulan pengetahuan manusia yang tersimpan dalam bentuk pola dan hubungan yang kompleks, sehingga dapat digunakan untuk berbagai macam aplikasi tanpa memerlukan pemrograman khusus atau pelatihan ulang. Karena telah mempelajari begitu banyak informasi selama proses pelatihan, model-model ini dapat menyelesaikan masalah baru hanya melalui pemberian prompt, yaitu dengan memberikan instruksi atau pertanyaan kepada model. Model kemudian memanfaatkan pola dan representasi pengetahuan yang telah dipelajarinya untuk menghasilkan keluaran yang paling mungkin sesuai dengan prompt yang diberikan.",
            "AI generatif baru mulai dikenal secara luas oleh masyarakat pada tahun 2022, tetapi sebenarnya teknologi ini memiliki sejarah yang panjang—eksperimen awal dalam pembuatan teks secara otomatis sudah dilakukan sejak tahun 1990-an. Edisi pertama buku ini, yang diterbitkan pada tahun 2017, bahkan telah memuat satu bab khusus yang cukup panjang berjudul “AI Generatif”, yang membahas teknik pembuatan teks dan gambar pada masa itu. Bab tersebut juga menyampaikan sebuah gagasan yang pada saat itu terdengar sangat tidak masuk akal, yaitu bahwa **“dalam waktu dekat”**, sebagian besar konten budaya yang kita konsumsi akan dibuat dengan bantuan AI."

          ]
        },
        {
          id: "Apa yang telah dicapai oleh deep learning sejauh ini",
          title : "Apa yang telah dicapai oleh deep learning sejauh ini",
          paragraphs : [
            "Selama satu dekade terakhir, deep learning telah menghasilkan sebuah revolusi teknologi yang luar biasa. Perkembangannya dimulai dengan pencapaian yang mengesankan dalam [tugas-tugas perseptual | adalah tugas yang berkaitan dengan kemampuan sistem komputer dalam mengenali dan memahami informasi yang diperoleh melalui data sensorik, seperti gambar, suara, dan video.] pada periode 2013 hingga 2017, kemudian mengalami kemajuan pesat dalam berbagai tugas natural language processing atau pemrosesan bahasa alami dari tahun 2017 hingga 2022, dan mencapai puncaknya melalui gelombang aplikasi generative AI yang transformatif sejak tahun 2022 hingga saat ini.",
            "Deep learning telah memungkinkan berbagai terobosan besar dalam permasalahan yang sangat kompleks dan selama bertahun-tahun sulit diselesaikan oleh mesin, di antaranya:",
            "* Chatbot yang lancar dan sangat serbaguna, seperti ChatGPT dan Gemini.",
            "* Asisten pemrograman, seperti GitHub Copilot.",
            "* Pembuatan gambar yang fotorealistis.",
            "* Klasifikasi gambar dengan kemampuan setara manusia.",
            "* Transkripsi ucapan dengan kemampuan setara manusia.",
            "* Transkripsi tulisan tangan dan teks cetak dengan kemampuan setara manusia.",
            "* Peningkatan yang signifikan dalam penerjemahan mesin.",
            "* Peningkatan yang signifikan dalam konversi teks menjadi suara (text-to-speech).",
            "* Kemampuan mengemudi secara otonom dengan tingkat kemampuan setara manusia, yang pada tahun 2025 telah diterapkan untuk penggunaan publik di Phoenix, San Francisco, Los Angeles, dan Austin.",
            "* Sistem rekomendasi yang semakin baik, seperti yang digunakan oleh YouTube, Netflix, dan Spotify.",
            "* Kemampuan bermain Go, Catur, dan Poker yang melampaui kemampuan manusia.",
            "Kita masih terus mengeksplorasi sejauh mana kemampuan deep learning dapat berkembang. Teknologi ini mulai diterapkan dengan tingkat keberhasilan yang tinggi pada berbagai permasalahan yang beberapa tahun lalu dianggap mustahil untuk diselesaikan. Contohnya adalah melakukan transkripsi otomatis terhadap puluhan ribu manuskrip kuno yang tersimpan di Arsip Rahasia Vatikan, mendeteksi dan mengklasifikasikan penyakit tanaman di lapangan hanya menggunakan sebuah smartphone, membantu [ahli onkologi | adalah dokter spesialis yang menangani penyakit kanker, mulai dari diagnosis, pengobatan, hingga pemantauan pasien.] maupun [radiologi| Ahli radiologi atau dokter spesialis radiologi adalah dokter yang memiliki keahlian dalam menggunakan dan menafsirkan hasil pemeriksaan pencitraan medis untuk membantu mendiagnosis penyakit atau kondisi tubuh.] dalam menginterpretasikan data pencitraan medis, serta memprediksi bencana alam seperti banjir, badai, bahkan gempa bumi.",
            "Dengan setiap pencapaian baru, kita semakin mendekati era ketika deep learning dapat membantu manusia dalam setiap aktivitas dan berbagai bidang kehidupan—mulai dari sains, kedokteran, manufaktur, energi, transportasi, pengembangan perangkat lunak, pertanian, hingga penciptaan karya seni."
          ]
        },
        {
          id: "ringkasan",
          title: "Ringkasan bab",
          paragraphs: [
            "Deep learning membuat komputer belajar representasi dari contoh. Ia berada di dalam bidang machine learning, yang juga merupakan bagian dari AI. Setelah memahami gambaran ini, kita siap mengenal tensor dan cara data diproses oleh model."

          ]
        }
      ]
    },
    { id: "bab-2", 
      number: "02", 
      title: "Tensor dan operasi dasar", 
      summary: "Bentuk data yang digunakan model dan cara mengolahnya.", 
      status: "Segera hadir", 
      notebook: null, 
      sections: [] },
    { id: "bab-3", number: "03", title: "Memulai jaringan saraf", summary: "Dari data, proses belajar, hingga evaluasi hasil.", status: "Segera hadir", notebook: null, sections: [] }
  ]
};
